# Perform a Gradle `build` which includes `assemble`, `check`, `test`
# of the projects, and uploads the generated artifacts.

name: Generate releaseble artifacts

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Runs this job in parallel for each sub-project
    strategy:
      matrix:
        project-dir:
          - strict-version-matcher-plugin
          - oss-licenses-plugin
          - google-services-plugin

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Perform a Gradle build
        working-directory: ./${{ matrix.project-dir }}
        run: ./gradlew publish
      - name: Upload generated artifacts
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: ${{ matrix.project-dir }}
          path: ./${{ matrix.project-dir }}/build/repo
          retention-days: 5
